### ISSUE TITLE
Won't log in

### ISSUE THREAD

**Issue by ThornedRose** [omgmog/lightdm-webkit-google#10]
Theme loads fine, comes up with my user (there's only my user on this system), password field appears fine. Password is entered correctly. Hitting 'Enter' on the keyboard results in nothing happening. Nothing happens if clicking "Sign In" either. Re-entering the password and/or pressing 'Enter'/"Sign In" again still doesn't log in.

I have the same problem with this theme: https://github.com/nejsan/lightdm-webkit-theme-tendou/
The Material theme (https://github.com/artur9010/lightdm-webkit-material) works fine.

OS: Arch Linux 
Kernel: x86_64 Linux 4.3.3-2-ARCH
Shell: bash 4.3.42
Resolution: 1920x1200
WM: OpenBox
DE: LXQt
WM Theme: Numix-ArchBlue
GTK Theme: Numix-ArchBlue [GTK2/3]
Icon Theme: Menda-Circle
Font: Noto Sans 10
CPU: Intel Core2 Quad CPU Q6600 @ 2.4GHz
GPU: GeForce GTX 650 Ti
RAM: 703MiB / 6979MiB

**Comment by PlasmaPower** [comment]
Are there any relevant errors in `journalctl -e`?

**Comment by ThornedRose** [comment]
After some troubleshooting, I found that this behaviour was occurring on all themes except the Material one.

I was able to fix it by editing `/etc/lightdm/lightdm.conf` and changing "user-session" from "default" to "lxqt" so it reads `user-session=lxqt`

For anyone else, they'll need to change "user-session" to whatever desktop (or window manager in the case of things like OpenBox) they use. :)

**Comment by omgmog** [comment]
Yep that's the solution. If you've already got lightdm up and running before using my theme, this won't be an issue.

This is mostly a problem because I don't present a control for changing the session.
