### ISSUE TITLE
hi need help does this still work

### ISSUE THREAD

**Issue by tjw0lf** [omgmog/lightdm-webkit-google#11]
I'm trying this but how do you get it to work i followed the directions to a T.

Does this only work in MATE becuase i seen in the theme index it had MATE in it. and i was trying this on xfce

Please help thank you

**Comment by omgmog** [comment]
Hi, have you tried editing `/etc/lightdm/lightdm.conf` and changing `user-session` from `default` to `xfce4-session` so it reads:

```
...
user-session=xfce4-session
...
```

Depending on your distro, there might be some additional dependenices for `xfce4-session`, or you might need to directly use `xfce` as the session.

**Comment by tjw0lf** [comment]
OK i will try that let you know. thanks for getting back to me

**Comment by tjw0lf** [comment]
Ok that did not work. Here's the log files tho and screenshot of whats happening.
[x-1-greeter.txt](https://github.com/omgmog/lightdm-webkit-google/files/211727/x-1-greeter.txt)
[webkit-greeter.txt](https://github.com/omgmog/lightdm-webkit-google/files/211728/webkit-greeter.txt)
![screenshot_2016-04-10_10-12-12](https://cloud.githubusercontent.com/assets/16531121/14409560/5bf685b8-ff06-11e5-8e60-123218745c3e.png)

**Comment by PlasmaPower** [comment]
@tjw0lf It would appear that the theme wasn't setup, what does your LightDM Webkit config look like? (Not the general LightDM config)

**Comment by omgmog** [comment]
@tjw0lf seems as if the theme doesn't exist.

Can you show me the output of:

```
ls /usr/share/lightdm-webkit/themes/
```

This should contain the `lightdm-webkit-google` folder.

If the folder is there, you then need to edit your `/etc/lightdm/lightdm-webkit-greeter.conf` to use the theme:

```
webkit-theme=lightdm-webkit-google
```

**Comment by tjw0lf** [comment]
Here you guys go.
![screenshot_2016-04-10_23-49-28](https://cloud.githubusercontent.com/assets/16531121/14413919/3227dc10-ff78-11e5-87d5-aa0b2a7115f5.png)
![screenshot_2016-04-10_23-51-04](https://cloud.githubusercontent.com/assets/16531121/14413923/3c1e303e-ff78-11e5-8160-713d4a0facfb.png)
![screenshot_2016-04-10_23-54-13](https://cloud.githubusercontent.com/assets/16531121/14413925/46e17846-ff78-11e5-8fcf-42111853b707.png)

Got webkit2 somebody on google+ said they got it working but i just seem to have bad luck. i need some help here. Also i i'm doing this in viratualbox but i don't see why that would effect anything.

If you go to Eye Candy Linux on google+ and then to Help tab you can see what somebody said they got it to work.

Hmm i can't :( :(

**Comment by omgmog** [comment]
So you're using `lightdm-webkit2-greeter`, rather than `lightdm-webkit-greeter`.

I'll set up a virtual machine and see if I can get my theme to work with that. The `lightdm-webkit2-greeter` JavaScript API might be very different to the one in `lightdm-webkit-greeter`.

**Comment by tjw0lf** [comment]
OK so i installed manjaro Arch xfce 16.06 pre and installed it in virtualbox just like straight Arch. I did everything the same as i did in straight Arch and the theme works fine.

Although in straight Arch it still does not work so something is missing or needs to be added not sure what they did differently.

**Comment by PlasmaPower** [comment]
@tjw0lf Are you sure you installed `lightdm-webkit-greeter` instead of `lightdm-webkit2-greeter`? If that's not the case, then it's probably an upstream lightdm-webkit-greeter bug.

**Comment by tjw0lf** [comment]
@PlasmaPower  I have lightdm-webkit2-greeter. But that is not the case of which one is installed because it works in manjaro Arch as i said. I have done the steps as i did in straight Arch. and in manjaro Arch it works fine. But not in straight Arch it does not.  SO something is messing or something else needs to be added
