### ISSUE TITLE
Cannot type password since lightdm 1.18.3

### ISSUE THREAD

**Issue by AWhetter** [omgmog/lightdm-webkit-google#15]
Since upgrading from lightdm 1.18.2 to 1.18.3, I cannot type in my password on startup, or focus the password field with the mouse. Instead I have to select a user (or reselect the currently selected user) to get the password field to focus so that I can type in it.

**Comment by omgmog** [comment]
Hi I'm not using Lightdm (or Linux with a GUI) much these days, so I'm not willing to support this very much. 

Are you able to hit tab to focus the password field?

The theme is built with HTML/Javascript/CSS so it should be pretty straight forward if you wish to poke around and try to fix the issue.

If you are able to fix it, submit a Pull Request and I'll merge your fix.
