### ISSUE TITLE
Webkit-greeter only changes after a restart, not when logging out or locking computer

### ISSUE THREAD

**Issue by Thatkookooguy** [omgmog/lightdm-webkit-google#8]
On Ubuntu 14.04, I installed the lightdm-webkit-greeter using `sudo apt-get install lightdm-webkit-greeter`

then, I did the following to get the greeter I wanted:

    cd /usr/share/lightdm-webkit/themes/
    sudo git clone http://github.com/omgmog/lightdm-webkit-google.git
    sudo sed -i 's/unity-greeter/lightdm-webkit-greeter/g' /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
    sudo sed -i 's/default/lightdm-webkit-google/g' /etc/lightdm/lightdm-webkit-greeter.conf

This works great and I get the login I want everytime I power up the computer.

The problem is, that when I log out or lock the computer, I get the regular Unity log-in screen.

Is there a way to change the greeter globaly? So on log out and lock I'll get the same greeter?

thanks!

**Comment by jgeis** [comment]
This __isn't__ a bug! It is because you technically aren't supposed to change this. The `unity-greeter` is like embedded into `unity`.

**Comment by PlasmaPower** [comment]
Is there a workaround?

**Comment by jgeis** [comment]
No, Unity has it embedded into the system. It is same with KDE and XFCE just uses the switch user screen or `xscreensaver`, if available.
